package com.mqttinsight.ui.form.panel;

import com.jgoodies.forms.layout.FormLayout;
import com.mqttinsight.exception.VerificationException;
import com.mqttinsight.mqtt.SecureSetting;

import javax.swing.*;

/**
 * @author ptma
 */
public class SecureEmptyPanel extends SecurePanel {

    private JPanel rootPanel;

    public SecureEmptyPanel() {
        super();
        $$$setupUI$$$();
    }

    @Override
    public JPanel getRootPanel() {
        return rootPanel;
    }

    @Override
    public void applyLanguage() {

    }

    @Override
    public void changeFieldsEnable(boolean enabled) {

    }

    @Override
    public void applySetting(SecureSetting setting) {
        // Do nothing
    }

    @Override
    public void resetFields() {

    }

    @Override
    public void verifyFields() throws VerificationException {

    }

    @Override
    public SecureSetting getSetting() throws VerificationException {
        return new SecureSetting();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("", ""));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
